import random

GERUND_ONLY = {
    'abhor': 'испытывать отвращение к',
    'acknowledge': 'признавать',
    'admit': 'признавать(ся)',
    'advise': 'советовать',
    'allow': 'разрешать',
    'anticipate': 'предвидеть, ожидать',
    'appreciate': 'ценить',
    'avoid': 'избегать',
    'be worth': 'стоить (того)',
    "can't help": 'не мочь удержаться',
    'celebrate': 'праздновать',
    'confess': 'признаваться',
    'consider': 'рассматривать',
    'defend': 'защищать',
    'delay': 'откладывать',
    'detest': 'сильно ненавидеть',
    'discontinue': 'прекращать',
    'discuss': 'обсуждать',
    'dislike': 'не любить',
    'dispute': 'оспаривать',
    'dread': 'страшиться, бояться',
    'endure': 'терпеть',
    'enjoy': 'наслаждаться',
    'escape': 'избегать, ускользать',
    'evade': 'уклоняться',
    'explain': 'объяснять',
    'fancy': 'хотеть (брит.)',
    'fear': 'бояться',
    'feel like': 'хотеться',
    'feign': 'притворяться',
    'finish': 'заканчивать',
    'forgive': 'прощать',
    'give up': 'бросать, сдаваться',
    'keep': 'продолжать',
    'keep on': 'продолжать настойчиво',
    'mention': 'упоминать',
    'mind': 'возражать',
    'miss': 'скучать по',
    'necessitate': 'делать необходимым',
    'omit': 'пропускать',
    'permit': 'разрешать',
    'picture': 'представлять',
    'postpone': 'откладывать',
    'practice': 'практиковать',
    'prevent': 'предотвращать',
    'put off': 'откладывать',
    'recall': 'вспоминать',
    'recollect': 'вспоминать',
    'recommend': 'рекомендовать',
    'report': 'докладывать',
    'resent': 'негодовать',
    'resist': 'сопротивляться',
    'resume': 'возобновлять',
    'risk': 'рисковать',
    'shirk': 'уклоняться от обязанностей',
    'shun': 'сторониться',
    'suggest': 'предлагать',
    'support': 'поддерживать',
    'tolerate': 'терпеть',
    'understand': 'понимать',
    'urge': 'побуждать',
    'warrant': 'оправдывать'
}

INFINITIVE_ONLY = {
    'agree': 'соглашаться',
    'appear': 'казаться',
    'arrange': 'договариваться',
    'ask': 'просить',
    'attempt': 'пытаться',
    'beg': 'умолять',
    'can afford': 'мочь себе позволить',
    "can't afford": 'не мочь себе позволить',
    "can't wait": 'не терпится',
    'care': 'заботиться',
    'chance': 'рискнуть',
    'choose': 'выбирать',
    'claim': 'утверждать',
    'come': 'приходить (к решению)',
    'consent': 'соглашаться',
    'dare': 'осмеливаться',
    'decide': 'решать',
    'demand': 'требовать',
    'deserve': 'заслуживать',
    'determine': 'решать',
    'elect': 'избирать',
    'endeavor': 'стараться',
    'expect': 'ожидать',
    'fail': 'не суметь',
    'get': 'получать',
    'grow up': 'вырасти (чтобы)',
    'guarantee': 'гарантировать',
    'hesitate': 'колебаться',
    'hope': 'надеяться',
    'hurry': 'спешить',
    'incline': 'быть склонным',
    'learn': 'учиться',
    'manage': 'справиться',
    'mean': 'намереваться',
    'need': 'нуждаться',
    'neglect': 'пренебрегать',
    'offer': 'предлагать',
    'pay': 'платить',
    'plan': 'планировать',
    'prepare': 'готовиться',
    'pretend': 'притворяться',
    'profess': 'заявлять',
    'promise': 'обещать',
    'prove': 'доказывать',
    'refuse': 'отказываться',
    'remain': 'оставаться',
    'request': 'просить (форм.)',
    'resolve': 'решать',
    'say': 'говорить',
    'seek': 'стремиться',
    'seem': 'казаться',
    'shudder': 'содрогаться',
    'strive': 'прилагать усилия',
    'struggle': 'бороться',
    'swear': 'клясться',
    'tend': 'иметь тенденцию',
    'threaten': 'угрожать',
    'turn out': 'оказываться',
    'venture': 'отважиться',
    'volunteer': 'вызватьcя',
    'wait': 'ждать',
    'want': 'хотеть',
    'wish': 'желать',
    'would like': 'хотел бы',
    'yearn': 'страстно желать'
}

IRREGULAR_VERBS = {
    "be": ("was/were", "been", "быть"),
    "become": ("became", "become", "становиться"),
    "break": ("broke", "broken", "ломать"),
    "buy": ("bought", "bought", "покупать"),
    "choose": ("chose", "chosen", "выбирать"),
    "come": ("came", "come", "приходить"),
    "do": ("did", "done", "делать"),
    "drink": ("drank", "drunk", "пить"),
    "drive": ("drove", "driven", "водить"),
    "eat": ("ate", "eaten", "есть"),
    "fall": ("fell", "fallen", "падать"),
    "feel": ("felt", "felt", "чувствовать"),
    "find": ("found", "found", "находить"),
    "forget": ("forgot", "forgotten", "забывать"),
    "get": ("got", "got", "получать"),
    "give": ("gave", "given", "давать"),
    "go": ("went", "gone", "идти"),
    "grow": ("grew", "grown", "расти"),
    "have": ("had", "had", "иметь"),
    "hear": ("heard", "heard", "слышать"),
    "hold": ("held", "held", "держать"),
    "know": ("knew", "known", "знать"),
    "leave": ("left", "left", "покидать"),
    "lose": ("lost", "lost", "терять"),
    "make": ("made", "made", "делать"),
    "meet": ("met", "met", "встречать"),
    "pay": ("paid", "paid", "платить"),
    "read": ("read", "read", "читать"),
    "ride": ("rode", "ridden", "ездить"),
    "run": ("ran", "run", "бегать"),
    "say": ("said", "said", "говорить"),
    "see": ("saw", "seen", "видеть"),
    "sell": ("sold", "sold", "продавать"),
    "send": ("sent", "sent", "отправлять"),
    "show": ("showed", "shown", "показывать"),
    "sing": ("sang", "sung", "петь"),
    "sit": ("sat", "sat", "сидеть"),
    "sleep": ("slept", "slept", "спать"),
    "speak": ("spoke", "spoken", "говорить"),
    "stand": ("stood", "stood", "стоять"),
    "steal": ("stole", "stolen", "красть"),
    "take": ("took", "taken", "брать"),
    "think": ("thought", "thought", "думать"),
    "understand": ("understood", "understood", "понимать"),
    "write": ("wrote", "written", "писать")
}

ALL_STRICT_VERBS = {**GERUND_ONLY, **INFINITIVE_ONLY}
VERB_TO_CATEGORY = {v: 'gerund' for v in GERUND_ONLY}
VERB_TO_CATEGORY.update({v: 'infinitive' for v in INFINITIVE_ONLY})

def get_random_verb():
    return random.choice(list(ALL_STRICT_VERBS.keys()))